services:
  postgres:
    image: postgres:17.0-alpine3.20
    env_file:
      - .env
    
    container_name: chat_app_postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1111}
      POSTGRES_DB: ${POSTGRES_DB:-chat_app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
