services:
  mysql_db:
    container_name: mysql_db_chat
    image: mysql:9.2.0
    restart: 'no'
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      
    volumes:
      - chatAppData:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
   
  phpmyadmin:
    container_name: phpmyadmin_chat
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    env_file: ./.env
    environment:
      - PMA_HOST=mysql_db
    ports:
      - 8080:80
    depends_on:
      - mysql_db

  redis:
    container_name: redis_db_chat
    image: redis:7.4.1-alpine3.20
    env_file:
     ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  chatAppData: